# basic github workflow to exercise ply tests
name: 'ply-demo ci'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  'build-test':
    steps:
    - uses: actions/checkout@v2
    - name: build ply-demo and run api tests
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: npm test
